from typing import Protocol

from app.domain.entities.client import Client


class ClientRepositoryPort(Protocol):
    async def get_all(self) -> list[Client]: ...

    async def get_by_id(self, client_id: int) -> Client | None: ...

    async def get_by_cpf_cnpj(self, cpf_cnpj: str) -> Client | None: ...

    async def add(self, client: Client) -> Client: ...

    async def update(self, client: Client) -> Client: ...

    async def delete(self, client_id: int) -> None: ...
