from typing import Protocol

from app.domain.entities.part import Part


class PartRepositoryPort(Protocol):
    async def get_all(self) -> list[Part]: ...

    async def get_by_id(self, part_id: int) -> Part | None: ...

    async def add(self, part: Part) -> Part: ...

    async def update(self, part: Part) -> Part: ...

    async def delete(self, part_id: int) -> None: ...
