from typing import Protocol

from app.domain.entities.service_type import ServiceType


class ServiceTypeRepositoryPort(Protocol):
    async def get_all(self) -> list[ServiceType]: ...

    async def get_by_id(self, service_type_id: int) -> ServiceType | None: ...

    async def get_by_name(self, name: str) -> ServiceType | None: ...

    async def add(self, service_type: ServiceType) -> ServiceType: ...

    async def update(self, service_type: ServiceType) -> ServiceType: ...

    async def delete(self, service_type_id: int) -> None: ...
