from typing import Protocol

from app.domain.entities.user import User


class UserRepositoryPort(Protocol):
    async def get_by_id(self, user_id: int) -> User | None: ...

    async def get_by_username(self, username: str) -> User | None: ...

    async def get_by_email(self, email: str) -> User | None: ...

    async def add(self, user: User) -> User: ...
