from typing import Protocol

from app.domain.entities.vehicle import Vehicle


class VehicleRepositoryPort(Protocol):
    async def get_all(self) -> list[Vehicle]: ...

    async def get_by_id(self, vehicle_id: int) -> Vehicle | None: ...

    async def get_by_plate(self, plate: str) -> Vehicle | None: ...

    async def get_by_client(self, client_id: int) -> list[Vehicle]: ...

    async def add(self, vehicle: Vehicle) -> Vehicle: ...

    async def update(self, vehicle: Vehicle) -> Vehicle: ...

    async def delete(self, vehicle_id: int) -> None: ...
